# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 91c0a585d07e6de185a6d227492d4980e5a9d51846c4195aa2952750f818bbc540a94961e3666d319c74ab77cb5a6e96d5b9f8a2eed3576bb48dc9a025ba41a9

test:
  secret_key_base: 347c23080109d19d2bbf55ffb5473849569ee465fe40b7165a5a64140d2f4309bb7993d3b9711ab7238f2b7da30a614afb161d95c0d06cf4ce57f1f9d96bd3ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
