# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
AdminUser.create!(email: 'admin@example.com', password: 'password', password_confirmation: 'password')

Brand.create(id: 1, marks: 'Bardot')
Brand.create(id: 2, marks: 'Luzette')
Brand.create(id: 3, marks: 'Mariposa')
Brand.create(id: 4, marks: '7 Esencias')
Brand.create(id: 5, marks: 'Adidas')
Brand.create(id: 6, marks: 'Aromascense')
Brand.create(id: 7, marks: 'Arruru')
Brand.create(id: 8, marks: 'Barbie')
Brand.create(id: 9, marks: 'Biofemenine')
Brand.create(id: 10, marks: 'Bioherbal')
Brand.create(id: 11, marks: 'BoyBoy Cars')
Brand.create(id: 12, marks: 'Chick')
Brand.create(id: 13, marks: 'Depilex')
Brand.create(id: 14, marks: 'Disney')
Brand.create(id: 15, marks: 'FreeStyle')
Brand.create(id: 16, marks: 'Leidy Star')
Brand.create(id: 17, marks: 'Menticol')
Brand.create(id: 18, marks: 'Mickey')
Brand.create(id: 19, marks: 'Nutrit')
Brand.create(id: 20, marks: 'PhineasYFerb')
Brand.create(id: 21, marks: 'Shock')
Brand.create(id: 22, marks: 'SoPretty')
Brand.create(id: 24, marks: 'Squash')
Brand.create(id: 25, marks: 'Stay Off')
Brand.create(id: 26, marks: 'Sun Pro')
Brand.create(id: 27, marks: 'Bisonte')
Brand.create(id: 28, marks: 'Bufalo')
Brand.create(id: 29, marks: 'Pequitas')
Brand.create(id: 30, marks: 'Dermanat')
Brand.create(id: 31, marks: 'Happy Secrets')
Brand.create(id: 32, marks: 'Piel de Armiño')
Brand.create(id: 33, marks: 'Dromatic')
Brand.create(id: 34, marks: 'Ice Color')
Brand.create(id: 35, marks: 'Delfin')
Brand.create(id: 36, marks: 'Magistral')
Brand.create(id: 37, marks: 'Wintex')
Brand.create(id: 38, marks: 'Lander')
Brand.create(id: 39, marks: 'LM')
Brand.create(id: 40, marks: 'Mawie')
Brand.create(id: 41, marks: 'N17')
Brand.create(id: 42, marks: 'Natulareza y Vida')
Brand.create(id: 43, marks: 'Barbasol')
Brand.create(id: 44, marks: 'Duo')
Brand.create(id: 45, marks: 'Flofi')
Brand.create(id: 46, marks: 'Fogo')
Brand.create(id: 47, marks: 'Kativa')
Brand.create(id: 48, marks: 'Moco de Gorila')
Brand.create(id: 49, marks: 'Colbon')
Brand.create(id: 50, marks: 'Cureband')
Brand.create(id: 51, marks: 'Lua')
Brand.create(id: 52, marks: 'Mk')
Brand.create(id: 53, marks: 'No 4')
Brand.create(id: 54, marks: 'Noraver')
Brand.create(id: 55, marks: 'Noxpirin')
Brand.create(id: 56, marks: 'Sundays')
Brand.create(id: 57, marks: 'Vitamina C')
Brand.create(id: 58, marks: 'Winny')
Brand.create(id: 59, marks: 'Yodora')
Brand.create(id: 60, marks: 'Vogue')

Place.create(id: 1, establishment: 'Miscelaneas')
Place.create(id: 2, establishment: 'Cacharrerías')
Place.create(id: 3, establishment: 'Droguerías')
Place.create(id: 4, establishment: 'Distribuidores de Belleza')
Place.create(id: 5, establishment: 'Supermercados')
Place.create(id: 6, establishment: 'Ferreterías')
Place.create(id: 7, establishment: 'Pañaleras')
Place.create(id: 8, establishment: 'Farmacias')
Place.create(id: 9, establishment: 'Tienas Naturistas')
Place.create(id: 10, establishment: 'Tiendas de Belleza')

Line.create(id: 1, category: 'Maquillaje')
Line.create(id: 2, category: 'Aseo y Hogar')
Line.create(id: 3, category: 'Farmacéutico')
Line.create(id: 4, category: 'Línea Bebes')
Line.create(id: 5, category: 'Solar')
Line.create(id: 6, category: 'Aseo Personal')
Line.create(id: 7, category: 'Capilares')
Line.create(id: 8, category: 'Cosmético')
Line.create(id: 9, category: 'Perfumería')

Company.create(id: 1, industry: 'Bardot')
Company.create(id: 2, industry: 'Belleza Express')
Company.create(id: 3, industry: 'Bisonte')
Company.create(id: 4, industry: 'Coaspharma')
Company.create(id: 5, industry: 'Dermanat')
Company.create(id: 6, industry: 'Domeco')
Company.create(id: 7, industry: 'Dromatic')
Company.create(id: 8, industry: 'Ice Color')
Company.create(id: 9, industry: 'Indulatex')
Company.create(id: 10, industry: 'Lander')
Company.create(id: 11, industry: 'LM')
Company.create(id: 12, industry: 'Mawie')
Company.create(id: 13, industry: 'N17')
Company.create(id: 14, industry: 'Natulareza y Vida')
Company.create(id: 15, industry: 'Prosalon')
Company.create(id: 16, industry: 'Tecnoquimicas')
Company.create(id: 17, industry: 'Vogue')